# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 06:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_linguagem', models.CharField(max_length=100, verbose_name='Linguagem')),
            ],
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userblocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComentFixies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('melhor_resposta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField(verbose_name='Coment\xe1rio')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao', models.IntegerField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fixies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolvido', models.BooleanField(default=False)),
                ('tem_melhor_resposta', models.BooleanField(default=False)),
                ('notificacao', models.IntegerField(default=0)),
                ('ativa_notificacao', models.BooleanField(default=True)),
                ('area', models.ManyToManyField(to='core.Areas')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('visualisada', models.BooleanField(default=False)),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao', models.IntegerField(default=0)),
                ('ativa_notificacao', models.BooleanField(default=True)),
                ('fixie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fixies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('post', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificacao', models.IntegerField(default=0)),
                ('ativa_notificacao', models.BooleanField(default=True)),
                ('exibir_perfil', models.BooleanField(default=True)),
                ('anexo', models.FileField(blank=True, upload_to=core.models.user_directory_path)),
                ('area', models.ManyToManyField(to='core.Areas')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('git', models.CharField(blank=True, max_length=100, verbose_name='Github')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_profileimage)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('visto_por_ultimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=False)),
                ('expert', models.BooleanField(default=False)),
                ('habilidades', models.ManyToManyField(to='core.Areas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favorites',
            name='fixie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fixies'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Post'),
        ),
        migrations.AddField(
            model_name='comentpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentfixies',
            name='fixie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fixies'),
        ),
        migrations.AddField(
            model_name='comentfixies',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
