# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentfixies_melhor_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentfixies',
            name='melhor_resposta',
        ),
        migrations.AddField(
            model_name='comentfixies',
            name='melhorresposta',
            field=models.BooleanField(default=False),
        ),
    ]
