# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fixies_resolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixies',
            name='tem_melhor_resposta',
            field=models.BooleanField(default=False),
        ),
    ]
