# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fixies_tem_melhor_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixies',
            name='notificacao',
            field=models.IntegerField(default=0),
        ),
    ]
