# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_fixies_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao', models.IntegerField(default=0)),
                ('fixie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fixies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
