# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
    ]
