# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_profile_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.CharField(blank=True, max_length=100, verbose_name='Github'),
        ),
    ]
