# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 14:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_exibir_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
