# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 19:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20161001_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anexo',
            field=models.FileField(blank=True, default='', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
