# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20161003_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anexo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
