# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 00:59
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20161003_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
    ]
