# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 23:30
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20161004_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagem_perfil',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_directory_profileimage),
        ),
    ]
