# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 01:04
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_profile_imagem_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_profileimage),
        ),
    ]
