# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_profile_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_linguagem', models.CharField(max_length=100, verbose_name='Linguagem')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='habilidades',
        ),
    ]
