# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_profile_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixies',
            name='area',
            field=models.ManyToManyField(to='core.Areas'),
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.ManyToManyField(to='core.Areas'),
        ),
    ]
