# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 01:48
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20161016_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anexo',
            field=models.FileField(blank=True, upload_to=core.models.user_directory_path),
        ),
    ]
