# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20161202_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visto_por_ultimo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
