# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_profile_visto_por_ultimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
