# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_anonfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expert',
            field=models.BooleanField(default=False),
        ),
    ]
